export const UPDATE_AD_SETTINGS_INITIATED = 'UPDATE_AD_SETTINGS_INITIATED'
export const UPDATE_AD_SETTINGS_SUCCESS = 'UPDATE_AD_SETTINGS_SUCCESS'
// export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS'
