export const UPDATE_COUNTRY_ID_FILTER_VALUE_LIST_SERVERS = 'UPDATE_COUNTRY_ID_FILTER_VALUE_LIST_SERVERS'

export const UPDATE_TYPE_FILTER_VALUE_LIST_SERVERS = 'UPDATE_TYPE_FILTER_VALUE_LIST_SERVERS'

export const UPDATE_PROTOCOL_FILTER_VALUE_LIST_SERVERS = 'UPDATE_PROTOCOL_FILTER_VALUE_LIST_SERVERS'

export const UPDATE_STATUS_FILTER_VALUE_LIST_SERVERS = 'UPDATE_STATUS_FILTER_VALUE_LIST_SERVERS'

export const UPDATE_CLOUD_ID_FILTER_VALUE_LIST_SERVERS = 'UPDATE_CLOUD_ID_FILTER_VALUE_LIST_SERVERS'

export const RESET_SERVERS_LIST_FILTERS = 'RESET_SERVERS_LIST_FILTERS'

export const SELECT_CHANGE_SERVERS_LIST = 'SELECT_CHANGE_SERVERS_LIST'

export const PAGE_CHANGE_LIST_SERVERS = 'PAGE_CHANGE_LIST_SERVERS'

export const CLEAR_PROTOCOL_FILTER = 'CLEAR_PROTOCOL_FILTER'
